CREATE TABLE public.companies (
  id text PRIMARY KEY,
  name text NOT NULL,
  industry text NOT NULL,
  city text NOT NULL,
  employees text NOT NULL DEFAULT '',
  website text NOT NULL DEFAULT '',
  verified boolean NOT NULL DEFAULT false,
  about text NOT NULL DEFAULT '',
  initials text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.jobs (
  id text PRIMARY KEY,
  title text NOT NULL,
  company_id text NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  category text NOT NULL,
  city text NOT NULL,
  remote boolean NOT NULL DEFAULT false,
  employment_type text NOT NULL,
  experience text NOT NULL DEFAULT '',
  education text NOT NULL DEFAULT '',
  salary_min integer NOT NULL DEFAULT 0,
  salary_max integer NOT NULL DEFAULT 0,
  posted_days_ago integer NOT NULL DEFAULT 0,
  deadline text NOT NULL DEFAULT '',
  applicants integer NOT NULL DEFAULT 0,
  skills text[] NOT NULL DEFAULT '{}',
  summary text NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  requirements text[] NOT NULL DEFAULT '{}',
  benefits text[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_jobs_company ON public.jobs(company_id);
CREATE INDEX idx_jobs_category ON public.jobs(category);
CREATE INDEX idx_jobs_city ON public.jobs(city);

GRANT SELECT ON public.companies TO anon;
GRANT SELECT ON public.companies TO authenticated;
GRANT ALL ON public.companies TO service_role;
GRANT SELECT ON public.jobs TO anon;
GRANT SELECT ON public.jobs TO authenticated;
GRANT ALL ON public.jobs TO service_role;

ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Companies are publicly readable" ON public.companies FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Jobs are publicly readable" ON public.jobs FOR SELECT TO anon, authenticated USING (true);

INSERT INTO public.companies (id,name,industry,city,employees,website,verified,about,initials) VALUES ('aster-tech','Aster Technologies','Software & IT','Addis Ababa','120-250','astertech.et',true,'Aster Technologies builds digital payment and lending infrastructure used by banks and microfinance institutions across Ethiopia.','AT');
INSERT INTO public.companies (id,name,industry,city,employees,website,verified,about,initials) VALUES ('abay-bank-digital','Abay Digital Bank','Banking & Finance','Addis Ababa','1000+','abaydigital.et',true,'A digital-first banking group serving retail and SME customers with mobile-first accounts, savings and credit products.','AD');
INSERT INTO public.companies (id,name,industry,city,employees,website,verified,about,initials) VALUES ('sheba-health','Sheba Health Group','Health & Medical','Bahir Dar','500-1000','shebahealth.et',true,'A network of clinics and diagnostic centres across the Amhara region focused on affordable primary care.','SH');
INSERT INTO public.companies (id,name,industry,city,employees,website,verified,about,initials) VALUES ('rift-logistics','Rift Valley Logistics','Logistics','Adama','250-500','riftlogistics.et',false,'Freight forwarding and last-mile distribution connecting Djibouti corridor imports to regional Ethiopian markets.','RL');
INSERT INTO public.companies (id,name,industry,city,employees,website,verified,about,initials) VALUES ('enat-agro','Enat Agro Industries','Engineering','Hawassa','500-1000','enatagro.et',true,'Agro-processing group operating coffee, oilseed and packaged food plants in the Sidama and Oromia regions.','EA');
INSERT INTO public.companies (id,name,industry,city,employees,website,verified,about,initials) VALUES ('lucy-learning','Lucy Learning','Education','Addis Ababa','50-120','lucylearning.et',false,'An education technology company producing Amharic and Afaan Oromo learning content for grades 1-12.','LL');
INSERT INTO public.jobs (id,title,company_id,category,city,remote,employment_type,experience,education,salary_min,salary_max,posted_days_ago,deadline,applicants,skills,summary,description,requirements,benefits) VALUES ('senior-frontend-engineer-aster','Senior Frontend Engineer','aster-tech','Software & IT','Addis Ababa',true,'Full-time','5+ years','BSc in Computer Science or related',65000,95000,2,'2026-09-05',48,ARRAY['React','TypeScript','Tailwind CSS','REST APIs','Testing']::text[],'Lead the web experience for a payments platform used by more than two million Ethiopians every month.','You will own the front-end architecture of our merchant and consumer dashboards, working closely with product design and backend teams to ship reliable, accessible interfaces on slow networks.',ARRAY['5+ years building production React applications','Strong TypeScript and modern CSS skills','Experience optimising for low-bandwidth mobile users','Comfortable mentoring mid-level engineers']::text[],ARRAY['Hybrid schedule','Private medical cover','Annual learning budget','Transport allowance']::text[]);
INSERT INTO public.jobs (id,title,company_id,category,city,remote,employment_type,experience,education,salary_min,salary_max,posted_days_ago,deadline,applicants,skills,summary,description,requirements,benefits) VALUES ('backend-engineer-nodejs-aster','Backend Engineer (Node.js)','aster-tech','Software & IT','Addis Ababa',false,'Full-time','3+ years','BSc in Software Engineering',52000,78000,5,'2026-08-28',91,ARRAY['Node.js','Express','PostgreSQL','Docker','CI/CD']::text[],'Build and scale the APIs behind lending, KYC and settlement services.','Join the core platform team designing resilient services that handle high transaction volumes with strict auditing and compliance requirements.',ARRAY['3+ years with Node.js in production','Solid relational database design skills','Understanding of authentication, authorisation and audit logging','Experience with containerised deployments']::text[],ARRAY['Performance bonus','Medical cover','Lunch provided']::text[]);
INSERT INTO public.jobs (id,title,company_id,category,city,remote,employment_type,experience,education,salary_min,salary_max,posted_days_ago,deadline,applicants,skills,summary,description,requirements,benefits) VALUES ('mobile-developer-flutter-abay','Mobile Developer (Flutter)','abay-bank-digital','Software & IT','Addis Ababa',false,'Full-time','2+ years','BSc in Computer Science',45000,68000,1,'2026-09-12',27,ARRAY['Flutter','Dart','REST APIs','Firebase']::text[],'Ship new features to the bank''s mobile app used by 4 million customers.','You will work on account opening, transfers and savings journeys, with a strong focus on offline resilience and Amharic localisation.',ARRAY['2+ years shipping Flutter apps to stores','Experience with secure storage and biometrics','Amharic localisation experience is a plus']::text[],ARRAY['Staff loan scheme','Pension','Annual bonus']::text[]);
INSERT INTO public.jobs (id,title,company_id,category,city,remote,employment_type,experience,education,salary_min,salary_max,posted_days_ago,deadline,applicants,skills,summary,description,requirements,benefits) VALUES ('credit-analyst-abay','SME Credit Analyst','abay-bank-digital','Banking & Finance','Addis Ababa',false,'Full-time','4+ years','BA in Accounting, Finance or Economics',38000,55000,8,'2026-08-22',64,ARRAY['Credit Risk','Financial Modelling','IFRS','Excel']::text[],'Assess and structure credit facilities for small and medium enterprises.','You will appraise loan applications, build cash-flow models and present recommendations to the credit committee.',ARRAY['4+ years in commercial or SME credit analysis','Strong financial statement analysis','Knowledge of NBE directives']::text[],ARRAY['Pension','Medical cover','Professional certification support']::text[]);
INSERT INTO public.jobs (id,title,company_id,category,city,remote,employment_type,experience,education,salary_min,salary_max,posted_days_ago,deadline,applicants,skills,summary,description,requirements,benefits) VALUES ('registered-nurse-sheba','Registered Nurse - Outpatient','sheba-health','Health & Medical','Bahir Dar',false,'Full-time','2+ years','BSc in Nursing',18000,26000,3,'2026-08-30',35,ARRAY['Patient Care','Triage','Record Keeping']::text[],'Provide outpatient care across our Bahir Dar clinic network.','You will triage patients, support physicians during consultations and maintain accurate clinical records.',ARRAY['Valid nursing licence','2+ years clinical experience','Fluent in Amharic and English']::text[],ARRAY['Shift allowance','Medical cover for family','Housing support']::text[]);
INSERT INTO public.jobs (id,title,company_id,category,city,remote,employment_type,experience,education,salary_min,salary_max,posted_days_ago,deadline,applicants,skills,summary,description,requirements,benefits) VALUES ('mechanical-engineer-enat','Plant Mechanical Engineer','enat-agro','Engineering','Hawassa',false,'Full-time','3+ years','BSc in Mechanical Engineering',32000,48000,6,'2026-09-01',22,ARRAY['Preventive Maintenance','Hydraulics','AutoCAD','Safety']::text[],'Keep our oilseed processing lines running at target availability.','Own the preventive maintenance programme, lead breakdown response and drive equipment reliability improvements.',ARRAY['3+ years in food or agro-processing plants','Hands-on maintenance planning experience','Strong safety mindset']::text[],ARRAY['Site housing','Transport','Overtime pay']::text[]);
INSERT INTO public.jobs (id,title,company_id,category,city,remote,employment_type,experience,education,salary_min,salary_max,posted_days_ago,deadline,applicants,skills,summary,description,requirements,benefits) VALUES ('digital-marketing-lead-lucy','Digital Marketing Lead','lucy-learning','Sales & Marketing','Addis Ababa',true,'Full-time','3+ years','BA in Marketing or Communications',30000,45000,4,'2026-09-10',58,ARRAY['Content Strategy','Meta Ads','SEO','Analytics']::text[],'Grow our learner base across Addis Ababa and regional cities.','You will run acquisition campaigns in Amharic and English, own the content calendar and report on funnel performance.',ARRAY['3+ years in digital marketing','Proven paid social performance','Excellent Amharic and English copywriting']::text[],ARRAY['Remote-friendly','Quarterly bonus','Device allowance']::text[]);
INSERT INTO public.jobs (id,title,company_id,category,city,remote,employment_type,experience,education,salary_min,salary_max,posted_days_ago,deadline,applicants,skills,summary,description,requirements,benefits) VALUES ('sales-representative-rift','Field Sales Representative','rift-logistics','Sales & Marketing','Adama',false,'Contract','1+ years','Diploma or above',14000,22000,10,'2026-08-20',73,ARRAY['B2B Sales','Negotiation','CRM']::text[],'Win new freight accounts along the Adama-Djibouti corridor.','You will prospect manufacturers and importers, quote freight services and manage the handover to operations.',ARRAY['1+ years field sales','Driving licence','Fluent Afaan Oromo and Amharic']::text[],ARRAY['Commission','Fuel allowance','Phone credit']::text[]);
INSERT INTO public.jobs (id,title,company_id,category,city,remote,employment_type,experience,education,salary_min,salary_max,posted_days_ago,deadline,applicants,skills,summary,description,requirements,benefits) VALUES ('warehouse-supervisor-rift','Warehouse Supervisor','rift-logistics','Logistics','Adama',false,'Full-time','3+ years','Diploma in Logistics or Supply Chain',16000,24000,7,'2026-08-26',41,ARRAY['Inventory Control','Team Leadership','WMS']::text[],'Run daily operations for a 6,000 sqm distribution warehouse.','Manage inbound and outbound flows, stock accuracy and a team of 24 warehouse staff across two shifts.',ARRAY['3+ years warehouse supervision','Inventory system experience','Strong reporting discipline']::text[],ARRAY['Shift allowance','Medical cover']::text[]);
INSERT INTO public.jobs (id,title,company_id,category,city,remote,employment_type,experience,education,salary_min,salary_max,posted_days_ago,deadline,applicants,skills,summary,description,requirements,benefits) VALUES ('curriculum-designer-lucy','Curriculum Designer (Afaan Oromo)','lucy-learning','Education','Addis Ababa',true,'Part-time','2+ years','BA in Education',12000,20000,12,'2026-08-18',19,ARRAY['Curriculum Design','Afaan Oromo','Assessment']::text[],'Adapt grade 5-8 science lessons into Afaan Oromo.','You will translate and adapt lesson plans, design assessments and review learner feedback with our content team.',ARRAY['Native Afaan Oromo','2+ years teaching or curriculum work','Comfortable with digital tools']::text[],ARRAY['Flexible hours','Fully remote']::text[]);
INSERT INTO public.jobs (id,title,company_id,category,city,remote,employment_type,experience,education,salary_min,salary_max,posted_days_ago,deadline,applicants,skills,summary,description,requirements,benefits) VALUES ('data-analyst-intern-aster','Data Analyst Intern','aster-tech','Software & IT','Addis Ababa',false,'Internship','Entry level','Final year student or fresh graduate',6000,9000,1,'2026-09-15',112,ARRAY['SQL','Python','Data Visualisation']::text[],'Six-month paid internship on the analytics team.','Support reporting on transaction trends, build dashboards and learn production analytics workflows.',ARRAY['Basic SQL','Curiosity and attention to detail','Available full-time for six months']::text[],ARRAY['Paid internship','Mentorship','Possible full-time offer']::text[]);
INSERT INTO public.jobs (id,title,company_id,category,city,remote,employment_type,experience,education,salary_min,salary_max,posted_days_ago,deadline,applicants,skills,summary,description,requirements,benefits) VALUES ('project-officer-enat','Community Project Officer','enat-agro','NGO & Development','Hawassa',false,'Contract','3+ years','BA in Development Studies or related',22000,32000,9,'2026-08-24',30,ARRAY['Stakeholder Engagement','M&E','Report Writing']::text[],'Lead smallholder farmer training programmes in the Sidama region.','Coordinate outgrower training, track programme indicators and report to partners and regional authorities.',ARRAY['3+ years in community programmes','Field-based work experience','Fluent Sidaamu Afoo a plus']::text[],ARRAY['Field allowance','Vehicle support']::text[]);